version: '3.8'

services:

  midi-creator:
    build:
      context: ./midi-creator
    container_name: midi-creator
    environment:
      - MIDI_FILES=vol-midi-files
      - MIDI_NUM=5
    volumes:
      - ./vol-midi-files:/app/vol-midi-files

  sound-creator:
    build:
      context: ./sound-creator
    container_name: sound-creator
    environment:
      - MIDI_FILES=vol-midi-files
      - WAV_FILES=vol-wav-files
    volumes:
      - ./vol-midi-files:/app/vol-midi-files
      - ./vol-wav-files:/app/vol-wav-files

  noise-generator:
    build:
      context: ./noise-generator
    container_name: noise-generator
    environment:
      - WAV_FILES=/app/vol-wav-files
      - NOISY_FILES=/app/vol-noisy-files
      - NOISE_LEVEL=0.02
    volumes:
      - ./vol-wav-files:/app/vol-wav-files
      - ./vol-noisy-files:/app/vol-noisy-files
    
  track-sender:
    build:
      context: ./track-sender
    container_name: track-sender
    environment:
      - NOISY_FILES=/app/vol-noisy-files
      - UPLOADER_CONVERTER_URL=http://uploader:8080/convert_audio
      - OUTPUT_FILES=/app/vol-output-files
      - UPLOADER_HEALTHCHECK=http://uploader:8080/healthcheck_global
    networks:
      - test-network   
    volumes:
      - ./vol-noisy-files:/app/vol-noisy-files
      - ./vol-output-files:/app/vol-output-files

  midi-comporator:
    build:
      context: ./midi-comporator
    container_name: midi-comporator
    environment:
      - ORIGINAL_MIDIS=/app/vol-midi-files
      - CONVERTED_MIDIS=/app/vol-output-files
    volumes:
      - ./vol-output-files:/app/vol-output-files
      - ./vol-midi-files:/app/vol-midi-files

networks:
  test-network:
    external: true
volumes:
  vol-midi-files:
    driver: local
  vol-wav-files:
    driver: local
  vol-noisy-files:
    driver: local
  vol-output-files:
    driver: local