version: '3.8'

services:

  midi-creator:
    build:
      context: ./midi-creator
    container_name: midi-creator
    environment:
      - MIDI_FILES=midi_files
      - MIDI_NUM=5
    volumes:
      - ./midi-files:/app/midi_files

  sound-creator:
    build:
      context: ./sound-creator
    container_name: sound-creator
    environment:
      - MIDI_FILES=midi_files
      - WAV_FILES=wav-files
    volumes:
      - ./midi-files:/app/midi_files
      - ./wav-files:/app/wav-files

  noise-generator:
    build:
      context: ./noise-generator
    container_name: noise-generator
    environment:
      - WAV_FILES=/app/wav-files
      - NOISY_FILES=/app/noisy-files
      - NOISE_LEVEL=0.02
    volumes:
      - ./wav-files:/app/wav-files
      - ./noisy-files:/app/noisy-files
    
  track-sender:
    build:
      context: ./track-sender
    container_name: track-sender
    environment:
      - NOISY_FILES=/app/noisy-files
      - UPLOADER_CONVERTER_URL=http://uploader:8080/convert_audio
      - OUTPUT_FILES=/app/output-files
      - UPLOADER_HEALTHCHECK=http://uploader:8080/healthcheck_global
    networks:
      - test-network   
    volumes:
      - ./noisy-files:/app/noisy-files
      - ./output-files:/app/output-files

networks:
  test-network:
    external: true
volumes:
  midi-files:
    driver: local
  wav-files:
    driver: local
  noisy-files:
    driver: local
  output-files:
    driver: local