---
apiVersion: v1
kind: Service
metadata:
  name: uploader-service
spec:
  selector:
    app: audio-uploader
  ports:
    - protocol: TCP
      port: 8080     
      targetPort: 8080
      nodePort: 30006
  type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audio-uploader
  template:
    metadata:
      labels:
        app: audio-uploader
    spec:
      containers:
        - name: audio-uploader
          image: brinckley/audio-uploader:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080