---
apiVersion: v1
kind: Service
metadata:
  name: converter-service
spec:
  selector:
    app: audio-converter
  ports:
    - protocol: TCP
      port: 8000     
      targetPort: 8000
      nodePort: 30007
  type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audio-converter
  template:
    metadata:
      labels:
        app: audio-converter
    spec:
      containers:
        - name: audio-converter
          image: brinckley/audio-converter:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/midis"
              name: file-storage
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: file-storage-pvc