global:
  scrape_interval:     5s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'uploader-servce'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['uploader:8080']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']