apiVersion: v1

kind: ConfigMap
metadata:
  name: uploader-env
  namespace: converter-app
data:
  FILE_STORAGE_PATH: /app/uploads

---
apiVersion: v1

kind: ConfigMap
metadata:
  name: audio-cleaner-env
  namespace: converter-app
data:
  FILE_STORAGE_PATH: /app/uploads

---
apiVersion: v1

kind: ConfigMap
metadata:
  name: basic-pitch-env
  namespace: converter-app
data:
  FILE_STORAGE_PATH: /app/uploads
  OUTPUT_PATH: /app/midis

---
apiVersion: v1

kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: converter-app
data:
  nginx.conf: |
    events {}

    http {
        upstream uploader_backend {
            server uploader:8080;
        }

        server {
            listen 80;

            server_name localhost;
            client_max_body_size 50M;

            location / {
                proxy_pass http://uploader_backend;
                proxy_http_version 1.1;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
