apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: converter-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
      
---
apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: midis-pvc
  namespace: converter-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
