apiVersion: v1

kind: Service
metadata:
  name: nginx
  namespace: converter-app
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

---
apiVersion: v1

kind: Service
metadata:
  name: uploader
  namespace: converter-app
spec:
  selector:
    app: uploader
  ports:
    - port: 8080

---
apiVersion: v1

kind: Service
metadata:
  name: audio-cleaner
  namespace: converter-app
spec:
  selector:
    app: audio-cleaner
  ports:
    - port: 8001

---
apiVersion: v1

kind: Service
metadata:
  name: basic-pitch-worker
  namespace: converter-app
spec:
  selector:
    app: basic-pitch-worker
  ports:
    - port: 8011
