apiVersion: v1

kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/uploads"

---
apiVersion: v1

kind: PersistentVolume
metadata:
  name: midis-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/midis"
